version: "3.8"

services:
  client:
    image: ghcr.io/kirshway/orgatime/client:latest
    networks:
      - local
      - server
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  server:
    image: ghcr.io/kirshway/orgatime/server:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      NODE_ENV: production
    networks:
      - local
    volumes:
      - uploads-data:/app/uploads
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    networks:
      - local
      - bridge
    user: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres-data:
  uploads-data:
networks:
  local:
  bridge:
    external: true
  server:
    external: true