version: "3.8"

services:
  postgres:
    restart: unless-stopped
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orgatime-dev
    user: postgres

volumes:
  postgres-data:
